[versions]
android-build-gradle = "7.3.1"
compose-ui-version = "1.1.1"
gson = "2.8.7"

[libraries]
android-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-build-gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }